name: Daily Options Update

concurrency:
  group: options-tracker-data
  cancel-in-progress: true

on:
  schedule:
    - cron: "10 23 * * *"   # runs daily at 23:10 UTC
  workflow_dispatch:         # enables the "Run workflow" button
  push:
    paths:
      - "config/options.json"
      - "scripts/**"

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run fetch script
        run: |
          python scripts/fetch_and_update.py
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/data/*.csv docs/data/*.txt || true
          if ! git diff --cached --quiet; then
            git commit -m "Daily data update"
            git push
          else
            echo "No changes to commit."
          fi
