name: Send weekly email (Brevo)

on:
  schedule:
    - cron: "0 7 * * 3"   # Wednesdays @ 07:00 UTC
  workflow_dispatch:

jobs:
  email:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt matplotlib numpy
      - name: Generate chart and send email (SMTP inline)
        env:
          REPORT_FROM_EMAIL: ${{ secrets.REPORT_FROM_EMAIL }}
          REPORT_TO_EMAILS:  ${{ secrets.REPORT_TO_EMAILS }}
          BREVO_SMTP_LOGIN:  ${{ secrets.BREVO_SMTP_LOGIN }}
          BREVO_SMTP_KEY:    ${{ secrets.BREVO_SMTP_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python scripts/email_report_smtp.py
